<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Euonia.Application" />
        <PackageReference Include="Euonia.Bus" />
        <PackageReference Include="Euonia.Bus.InMemory" />
        <PackageReference Include="Euonia.Bus.RabbitMq" />
        <PackageReference Include="Euonia.Business" />
        <PackageReference Include="Euonia.Domain" />
        <PackageReference Include="Euonia.Mapping.Automapper" />
        <PackageReference Include="Euonia.Modularity" />
        <PackageReference Include="Euonia.Pipeline" />
        <PackageReference Include="Euonia.Validation" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Persistent\Starfish.Persistent.csproj" />
        <ProjectReference Include="..\Starfish.Shared\Starfish.Shared.csproj" />
        <ProjectReference Include="..\Starfish.Toolkit\Starfish.Toolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="$(RootNamespace).Properties" />
        <Using Include="Nerosoft.Starfish.Shared.Properties" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\CommonResources.Designer.cs">
            <DependentUpon>CommonResources.resx</DependentUpon>
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
        </Compile>
        <Compile Update="Properties\IdentityResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>IdentityResources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\CommonResources.resx">
            <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
            <Generator>ResXFileCodeGenerator</Generator>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\IdentityResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>IdentityResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
