<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Euonia.Linq" />
        <PackageReference Include="Euonia.Mapping.Automapper" />
        <PackageReference Include="Euonia.Repository.EfCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Domain\Starfish.Domain.csproj" />
    </ItemGroup>

</Project>
