<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Euonia.Bus" />
        <PackageReference Include="Euonia.Caching.Memory" />
        <PackageReference Include="Euonia.Caching.Redis" />
        <PackageReference Include="Euonia.Caching.Runtime" />
        <PackageReference Include="Euonia.Linq" />
        <PackageReference Include="Euonia.Mapping.Automapper" />
        <PackageReference Include="Euonia.Repository.EfCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="MySql.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Persistent\Starfish.Persistent.csproj" />
        <ProjectReference Include="..\Starfish.Infrastructure\Starfish.Infrastructure.csproj" />
        <ProjectReference Include="..\Starfish.Toolkit\Starfish.Toolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="$(RootNamespace).Properties" />
        <Using Include="Nerosoft.Starfish.Infrastructure.Properties" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\IdentityResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>IdentityResources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\CommonResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>CommonResources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\IdentityResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>IdentityResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\CommonResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
