<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Euonia.Bus.InMemory" />
        <PackageReference Include="Euonia.Bus.RabbitMq" />
        <PackageReference Include="FluentHttpClient" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Domain\Starfish.Domain.csproj" />
        <ProjectReference Include="..\Starfish.Repository\Starfish.Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="$(RootNamespace).Properties" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\CommonResources.Designer.cs">
            <DependentUpon>CommonResources.resx</DependentUpon>
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
        </Compile>
        <Compile Update="Properties\IdentityResources.Designer.cs">
            <DependentUpon>IdentityResources.resx</DependentUpon>
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
        </Compile>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\CommonResources.resx">
            <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
            <Generator>ResXFileCodeGenerator</Generator>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\IdentityResources.resx">
            <LastGenOutput>IdentityResources.Designer.cs</LastGenOutput>
            <Generator>ResXFileCodeGenerator</Generator>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
