<Project Sdk="Microsoft.NET.Sdk.Web">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated;Microsoft.AspNetCore.Http.Validation.Generated;</InterceptorsNamespaces> 
        <InterceptorsPreventNamespaces>$(InterceptorsPreventNamespaces);OpenIddict</InterceptorsPreventNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Euonia.Hosting" />
        <PackageReference Include="Euonia.Modularity" />
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Enrichers.Environment" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Facade\Starfish.Facade.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="$(RootNamespace).Properties" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\CommonResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>CommonResources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\HomeResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>HomeResources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\LoginResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>LoginResources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\CommonResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\HomeResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>HomeResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\LoginResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>LoginResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
