<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Infrastructure\Starfish.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Nerosoft.Starfish.Infrastructure.Properties" />
    </ItemGroup>

</Project>
